const { GoogleGenAI } = require("@google/genai")
const { z } = require("zod")
const { zodToJsonSchema } = require("zod-to-json-schema")
const puppeteer = require("puppeteer")

const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY
})


const interviewReportSchema = z.object({
    title: z.string().describe("Job title for which the interview report is generated"),

    matchScore: z.number().describe("A score between 0 and 100 indicating how well the candidate matches the job"),

    technicalQuestions: z.array(
        z.object({
            question: z.string().describe("Technical interview question")
        })
    ).describe("List of technical interview questions"),

    behavioralQuestions: z.array(
        z.object({
            question: z.string().describe("Behavioral interview question")
        })
    ).describe("List of behavioral interview questions"),

    skillGaps: z.array(
        z.object({
            skill: z.string().describe("Missing skill or improvement area")
        })
    ).describe("List of skill gaps"),

    preparationPlan: z.array(
        z.object({
            task: z.string().describe("Preparation task for interview")
        })
    ).describe("Preparation roadmap for interview")
})

async function generateInterviewReport({ resume, selfDescription, jobDescription }) {


    const prompt = `
                        You are an expert technical interviewer.

                        Analyze the candidate profile and generate an interview preparation report.

                        Resume:
                        ${resume}

                        Self Description:
                        ${selfDescription}

                        Job Description:
                        ${jobDescription}

                        IMPORTANT:
                        - Return ONLY valid JSON.
                        - Follow the schema EXACTLY.
                        - Do not add extra fields.
                        - Do not rename fields.
                        - Do not return markdown.
                        - Do not return explanations outside JSON.

                        Generate:

                        1. title
                        - Extract job title from job description.

                        2. matchScore
                        - Integer between 0 and 100.

                        3. technicalQuestions
                        - Exactly 5 technical interview questions.

                        4. behavioralQuestions
                        - Exactly 3 behavioral interview questions.

                        5. skillGaps
                        - Exactly 3 skill gaps.

                        6. preparationPlan
                        - Exactly 5 preparation tasks.

                        Return only JSON.

`

    const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: zodToJsonSchema(interviewReportSchema),
        }
    })

    return JSON.parse(response.text)


}



async function generatePdfFromHtml(htmlContent) {
    const browser = await puppeteer.launch()
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: "networkidle0" })

    const pdfBuffer = await page.pdf({
        format: "A4", margin: {
            top: "20mm",
            bottom: "20mm",
            left: "15mm",
            right: "15mm"
        }
    })

    await browser.close()

    return pdfBuffer
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {

    const resumePdfSchema = z.object({
        html: z.string().describe("The HTML content of the resume which can be converted to PDF using any library like puppeteer")
    })

    const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                    `

    const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: zodToJsonSchema(resumePdfSchema),
        }
    })


    const jsonContent = JSON.parse(response.text)

    const pdfBuffer = await generatePdfFromHtml(jsonContent.html)

    return pdfBuffer

}

module.exports = { generateInterviewReport, generateResumePdf }